### ISSUE TITLE
"About device" in Settings loads for more than a minute (Miyoo Mini Plus)

### ISSUE THREAD

**Issue by pig-cop** [OnionUI/MainUI-issues#17]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0-RC

### Miyoo Firmware Version

202306092122

### Provide a clear and concise description of the issue

After turning on the Miyoo Mini Plus opening the "About device" section in Settings freezes for more than a minute before opening.
After that it opens normally.

### Steps to Reproduce

- Turn on the Miyoo Mini Plus
- Go to: Settings > About device

### Provide any additional context or information that may help us investigate your issue

It's worth noting that the "Onion OTA update" app will freeze for the same amount of time if "About device" is not manually opened after the device is started and before opening the OTA update. I guess it needs to retrieve the same device information before proceeding.

**Comment by obloch13** [comment]
I have the same issue with the firmware version 202306282128.

**Comment by specialmixer** [comment]
Same here.
Tested it with 2 different Miyoo Mini Plus, with FW 0609 and 0628 and 4 different SD cards
The same problem also occurs when clicking OTA Update.
After waiting 90 seconds it works.
But the checkdisk prompt is not displayed on OTA.
Once you have waited 90 seconds, it works immediately until after a restart.
I've already been in touch the developer on FB.
Unfortunately there is no solution so far.

**Comment by pig-cop** [comment]
Try what I've done here: https://github.com/OnionUI/Onion/issues/1137#issuecomment-1705640034

This solved the issue for me!
